FINN-13: Version control the installed XRT version.
Docker installs XRT when building the container. This patch
allows the maintainer to set the Vitis tools version and the
hash of the supported XRT version verified to work with FINN.
This is the way XRT versioning is managed in AWS instances.

FINN-13 was caused by using 2022.1 Vitis and an old XRT version
in usage during 2020.1. Version controlling the sets of tools
will prevent bugs like this from recurring.

Signed-off-by: Fionn O'Donohoe <fionno@xilinx.com>

diff --git a/docker/Dockerfile.finn b/docker/Dockerfile.finn
--- a/docker/Dockerfile.finn
+++ b/docker/Dockerfile.finn
@@ -69,6 +69,23 @@ RUN locale-gen "en_US.UTF-8"
 RUN wget https://www.xilinx.com/bin/public/openDownload?filename=$XRT_DEB_VERSION.deb -O /tmp/$XRT_DEB_VERSION.deb
 RUN apt install -y /tmp/$XRT_DEB_VERSION.deb
 RUN rm /tmp/$XRT_DEB_VERSION.deb
+RUN if [ ! -f "/opt/xilinx/xrt/include/version.h" ]; then \
+    echo "ERROR: XRT not installed. Please install XRT" ; exit 1 ; \
+  fi ;
+
+# Inherit the xrt_supported_versions arg, a file, and copy it to docker
+ARG xrt_supported_versions
+ADD $xrt_supported_versions ./
+ARG XILINX_VERSION
+RUN echo "XRT installed. proceeding to check version compatibility" ; \
+  xrt_build_ver="$XILINX_VERSION:"$(grep 'xrt_build_version_hash\[\]' /opt/xilinx/xrt/include/version.h | sed 's/";//' | sed 's/^.*"//') ; \
+  if grep -Fxq "$xrt_build_ver" $xrt_supported_versions ; then \
+      echo "XRT version $xrt_build_ver is supported." ; \
+      echo "XRT Runtime setup Done" ; \
+    else \
+      echo "ERROR: $xrt_build_ver does not match supported versions" ; \
+      exit 1 ; \
+  fi ;
 
 # versioned Python package requirements for FINN compiler
 # these are given in requirements.txt
